using System.Text;
using BaumConfigureGUI.Models;

namespace BaumConfigureGUI.Services;

public static class CloudInitService
{
    public static string GenerateMetaData(NodeConfig c) =>
        $"instance-id: node{c.NodeNumber}\nlocal-hostname: {c.Hostname}\n";

    public static string GenerateUserData(NodeConfig c)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#cloud-config");
        sb.AppendLine($"# Node {c.NodeNumber} — {c.Hostname}");
        sb.AppendLine($"# Generated by BaumConfigure");
        sb.AppendLine();
        sb.AppendLine($"hostname: {c.Hostname}");
        sb.AppendLine("manage_etc_hosts: true");
        sb.AppendLine();

        // ── Users ─────────────────────────────────────────────────────────────
        sb.AppendLine("users:");
        sb.AppendLine($"  - name: {c.Username}");
        sb.AppendLine("    groups: [sudo, docker]");
        sb.AppendLine("    shell: /bin/bash");
        sb.AppendLine("    sudo: ALL=(ALL) NOPASSWD:ALL");

        if (!string.IsNullOrWhiteSpace(c.SshPublicKey))
        {
            sb.AppendLine("    ssh_authorized_keys:");
            sb.AppendLine($"      - {c.SshPublicKey.Trim()}");
        }

        if (!string.IsNullOrWhiteSpace(c.PasswordHash))
        {
            sb.AppendLine($"    passwd: \"{c.PasswordHash.Trim()}\"");
            sb.AppendLine("    lock_passwd: false");
        }

        sb.AppendLine();
        sb.AppendLine($"ssh_pwauth: {(c.SshPasswordAuth ? "true" : "false")}");
        sb.AppendLine($"disable_root: {(c.DisableRoot ? "true" : "false")}");
        sb.AppendLine();

        // ── Packages ──────────────────────────────────────────────────────────
        var packages = new List<string> { "curl", "vim", "htop", "git", "unattended-upgrades", "apt-listchanges" };
        if (c.InstallGlusterServer) packages.Add("glusterfs-server");
        if (c.InstallGlusterClient) packages.Add("glusterfs-client");
        if (c.InstallDocker)        packages.Add("docker.io");

        foreach (var extra in c.ExtraPackages.Split(new[] { '\n', ',', ' ' }, StringSplitOptions.RemoveEmptyEntries))
            packages.Add(extra.Trim());

        sb.AppendLine("packages:");
        foreach (var pkg in packages)
            sb.AppendLine($"  - {pkg}");
        sb.AppendLine();

        // ── runcmd ────────────────────────────────────────────────────────────
        sb.AppendLine("runcmd:");
        sb.AppendLine("  - systemctl enable --now ssh");
        if (c.InstallGlusterServer)
            sb.AppendLine("  - systemctl enable --now glusterd");
        sb.AppendLine($"  - timedatectl set-timezone {c.Timezone}");
        sb.AppendLine("  - dpkg-reconfigure -plow unattended-upgrades");

        // RK1 needs IPVS kernel modules for Docker Swarm networking
        if (c.NodeNumber == 1)
        {
            sb.AppendLine("  - modprobe ip_vs");
            sb.AppendLine("  - modprobe ip_vs_rr");
            sb.AppendLine("  - modprobe ip_vs_wrr");
            sb.AppendLine("  - modprobe ip_vs_sh");
            sb.AppendLine("  - modprobe nf_conntrack");
            sb.AppendLine("  - \"echo -e 'ip_vs\\nip_vs_rr\\nip_vs_wrr\\nip_vs_sh\\nnf_conntrack' > /etc/modules-load.d/ipvs.conf\"");
        }

        foreach (var cmd in c.ExtraRuncmds.Split('\n', StringSplitOptions.RemoveEmptyEntries))
            sb.AppendLine($"  - {cmd.Trim()}");

        sb.AppendLine();

        // ── /etc/hosts entries ────────────────────────────────────────────────
        bool hasIps = !string.IsNullOrWhiteSpace(c.RK1Ip)
                   || !string.IsNullOrWhiteSpace(c.Compute3Ip)
                   || !string.IsNullOrWhiteSpace(c.Compute4Ip);
        if (hasIps)
        {
            sb.AppendLine("write_files:");
            sb.AppendLine("  - path: /etc/hosts");
            sb.AppendLine("    append: true");
            sb.AppendLine("    content: |");
            sb.AppendLine("      # Turing Pi cluster nodes");
            if (!string.IsNullOrWhiteSpace(c.RK1Ip))
                sb.AppendLine($"      {c.RK1Ip.PadRight(20)} TuringPiRK1");
            if (!string.IsNullOrWhiteSpace(c.Compute3Ip))
                sb.AppendLine($"      {c.Compute3Ip.PadRight(20)} TuringPICompute3");
            if (!string.IsNullOrWhiteSpace(c.Compute4Ip))
                sb.AppendLine($"      {c.Compute4Ip.PadRight(20)} TuringPICompute4");
        }

        return sb.ToString();
    }
}
