using System.Text;
using BaumConfigureGUI.Models;

namespace BaumConfigureGUI.Services;

public static class CloudInitService
{
    public static string GenerateMetaData(NodeConfig c) =>
        $"instance-id: {c.Hostname}-{Guid.NewGuid().ToString("N")[..8]}\nlocal-hostname: {c.Hostname}\n";

    /// <summary>
    /// Returns a netplan v2 YAML string for /etc/netplan/90-baum-network.yaml,
    /// or null if network configuration is disabled.
    /// </summary>
    public static string? GenerateNetplanConfig(NodeConfig c)
    {
        if (!c.ConfigureNetwork) return null;

        bool isWifi = c.NetworkType == "wifi";
        var sb = new StringBuilder();
        sb.AppendLine("network:");
        sb.AppendLine("  version: 2");

        // Always include a DHCP ethernet fallback when WiFi is primary
        if (isWifi)
        {
            sb.AppendLine("  ethernets:");
            sb.AppendLine("    eth0:");
            sb.AppendLine("      dhcp4: true");
            sb.AppendLine("      optional: true");
        }

        sb.AppendLine(isWifi ? "  wifis:" : "  ethernets:");
        sb.AppendLine(isWifi ? "    wlan0:" : "    eth0:");

        if (c.UseDhcp)
        {
            sb.AppendLine("      dhcp4: true");
        }
        else
        {
            sb.AppendLine("      dhcp4: false");
            if (!string.IsNullOrWhiteSpace(c.StaticIp))
                sb.AppendLine($"      addresses: [{c.StaticIp}]");
            if (!string.IsNullOrWhiteSpace(c.Gateway))
                sb.AppendLine($"      routes:");
                sb.AppendLine($"        - to: default");
                sb.AppendLine($"          via: {c.Gateway}");
            var dns = c.DnsServers
                .Split(new[] { ',', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            if (dns.Length > 0)
            {
                sb.AppendLine("      nameservers:");
                sb.AppendLine($"        addresses: [{string.Join(", ", dns)}]");
            }
        }

        if (isWifi && !string.IsNullOrWhiteSpace(c.WifiSsid))
        {
            sb.AppendLine("      access-points:");
            sb.AppendLine($"        \"{c.WifiSsid}\":");
            if (!string.IsNullOrWhiteSpace(c.WifiPassword))
                sb.AppendLine($"          password: \"{c.WifiPassword}\"");
        }

        return sb.ToString();
    }

    public static string GenerateUserData(NodeConfig c)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#cloud-config");
        sb.AppendLine($"# Generated by BaumConfigure — {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine();
        sb.AppendLine($"hostname: {c.Hostname}");
        sb.AppendLine("manage_etc_hosts: true");
        sb.AppendLine();

        // ── Users ─────────────────────────────────────────────────────────────
        sb.AppendLine("users:");
        sb.AppendLine($"  - name: {c.Username}");

        var groups = new List<string> { "sudo" };
        if (c.InstallDocker) groups.Add("docker");
        sb.AppendLine($"    groups: [{string.Join(", ", groups)}]");
        sb.AppendLine("    shell: /bin/bash");
        sb.AppendLine("    sudo: ALL=(ALL) NOPASSWD:ALL");

        if (!string.IsNullOrWhiteSpace(c.PasswordHash))
        {
            sb.AppendLine($"    passwd: \"{c.PasswordHash.Trim()}\"");
            sb.AppendLine("    lock_passwd: false");
        }

        sb.AppendLine();
        sb.AppendLine("ssh_pwauth: true");
        sb.AppendLine("disable_root: true");
        sb.AppendLine();

        // ── Packages ──────────────────────────────────────────────────────────
        var packages = new List<string> { "curl", "vim", "htop", "git", "unattended-upgrades", "apt-listchanges" };

        if (c.InstallDocker)
        {
            // Use official Docker install script via runcmd; apt docker.io is stale
        }
        if (c.InstallK8s)
        {
            packages.AddRange(["apt-transport-https", "ca-certificates", "gpg"]);
        }

        foreach (var extra in c.ExtraPackages.Split(new[] { '\n', ',', ' ' }, StringSplitOptions.RemoveEmptyEntries))
            packages.Add(extra.Trim());

        sb.AppendLine("packages:");
        foreach (var pkg in packages)
            sb.AppendLine($"  - {pkg}");
        sb.AppendLine();

        // ── runcmd ────────────────────────────────────────────────────────────
        sb.AppendLine("runcmd:");
        sb.AppendLine("  - systemctl enable --now ssh");
        sb.AppendLine($"  - timedatectl set-timezone {c.Timezone}");
        sb.AppendLine("  - dpkg-reconfigure -plow unattended-upgrades");

        if (c.InstallDocker)
        {
            sb.AppendLine("  # Install Docker via official script");
            sb.AppendLine("  - curl -fsSL https://get.docker.com | sh");
            sb.AppendLine($"  - usermod -aG docker {c.Username}");
            sb.AppendLine("  - systemctl enable --now docker");
        }

        if (c.InstallK8s)
        {
            sb.AppendLine("  # Install kubeadm, kubelet, kubectl");
            sb.AppendLine("  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg");
            sb.AppendLine("  - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /' > /etc/apt/sources.list.d/kubernetes.list");
            sb.AppendLine("  - apt-get update");
            sb.AppendLine("  - apt-get install -y kubelet kubeadm kubectl");
            sb.AppendLine("  - apt-mark hold kubelet kubeadm kubectl");
            sb.AppendLine("  - systemctl enable --now kubelet");
        }

        if (c.InstallPortainer)
        {
            sb.AppendLine("  # Install Portainer CE (requires Docker)");
            sb.AppendLine("  - docker volume create portainer_data");
            sb.AppendLine("  - docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest");
        }

        foreach (var cmd in c.ExtraRuncmds.Split('\n', StringSplitOptions.RemoveEmptyEntries))
            sb.AppendLine($"  - {cmd.Trim()}");

        return sb.ToString();
    }
}
